### ISSUE TITLE
pmdCE: 2 @curvedir needed

### ISSUE THREAD

**Issue by JoachimIffland** [Freischuetz-Digital/proofMEIdata#25]
xml:id D1849_mov6_measure79_ce2

**Comment by bwbohl** [comment]
Do I understand right, that you need 2 different @curvedir?
Is there an example you can provide?

----- Reply message -----
Von: "JoachimIffland" <notifications@github.com>
An: "Freischuetz-Digital/proofMEIdata" <proofMEIdata@noreply.github.com>
Cc: "Benjamin W. Bohl" <bohl@edirom.de>
Betreff: [proofMEIdata] pmdCE: 2 @curvedir needed (#25)
Datum: Di., Jan. 27, 2015 13:02


Assigned #25 to @bwbohl.

---
Reply to this email directly or view it on GitHub:
https://github.com/Freischuetz-Digital/proofMEIdata/issues/25#event-225305027

**Comment by bwbohl** [comment]
Ok, oversaw the provided xml:id. Forget he previous example request

----- Reply message -----
Von: "JoachimIffland" <notifications@github.com>
An: "Freischuetz-Digital/proofMEIdata" <proofMEIdata@noreply.github.com>
Cc: "Benjamin W. Bohl" <bohl@edirom.de>
Betreff: [proofMEIdata] pmdCE: 2 @curvedir needed (#25)
Datum: Di., Jan. 27, 2015 13:02


xml:id D1849_mov6_measure79_ce2

---
Reply to this email directly or view it on GitHub:
https://github.com/Freischuetz-Digital/proofMEIdata/issues/25

**Comment by bwbohl** [comment]
![bildschirmfoto 2015-01-30 um 14 05 39](https://cloud.githubusercontent.com/assets/2430401/5976008/319371e8-a889-11e4-9a4c-7fe5cc246dfe.png)

**Comment by bwbohl** [comment]
for the moment we might just add a third possible value 'mixed'.
