### ISSUE TITLE
pmdCE: Two @curve.dir: 2nd case

### ISSUE THREAD

**Issue by JoachimIffland** [Freischuetz-Digital/proofMEIdata#37]
xml:id="A_mov8_measure17_ce4"
curve ist above on p128, below on
![curvedir a_mov8 m17 s8 p128-129](https://cloud.githubusercontent.com/assets/8817554/6124252/1aa79f82-b10c-11e4-85bb-5d0679e81b82.png)
 p129

**Comment by bwbohl** [comment]
same as #25
