### ISSUE TITLE
pmdCE: endid & mRpt

### ISSUE THREAD

**Issue by JoachimIffland** [Freischuetz-Digital/proofMEIdata#40]
xml:id="A_mov8_measure85_ce8"
![endid mrpt a_mov8 m85 s7 p136](https://cloud.githubusercontent.com/assets/8817554/6127544/7c042140-b12c-11e4-8309-b1a6c530e9e4.png)

See also A_p151_m46_s11 as a special case

**Comment by bwbohl** [comment]
This is a major problem and will lead to a major conceptual change in our data workflow. Shortcuts for events will have to be resolved before loading the data into this tool!
